language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
branches:
  only:
    - master
    - /^dev\/.*$/
notifications:
  email: false
after_success:
  - mvn clean cobertura:cobertura coveralls:report
